version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=books_db
      - POSTGRES_USER=books_user
      - POSTGRES_PASSWORD=password

  web:
    build: .
    command: waitress-serve --port=8080 books.wsgi:application
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db